2024-03-28 06:38:45,797 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 06:38:45,797 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 06:47:36,363 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:36] "GET / HTTP/1.1" 200 -
2024-03-28 06:47:40,978 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:40] "GET / HTTP/1.1" 200 -
2024-03-28 06:47:43,113 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:43] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:47:45,777 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-03-28 06:47:50,860 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:50] "GET /login HTTP/1.1" 200 -
2024-03-28 06:47:52,945 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:47:52] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:48:03,156 INFO flask_wtf.csrf The CSRF tokens do not match.
2024-03-28 06:48:03,157 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:48:03] "POST /login HTTP/1.1" 200 -
2024-03-28 06:48:05,507 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:48:05] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:48:16,750 INFO flask_wtf.csrf The CSRF tokens do not match.
2024-03-28 06:48:16,750 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:48:16] "POST /login HTTP/1.1" 200 -
2024-03-28 06:48:18,840 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:48:18] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:49:30,394 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:49:30] "GET /register HTTP/1.1" 200 -
2024-03-28 06:49:32,546 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:49:32] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:50:18,614 INFO flask_wtf.csrf The CSRF tokens do not match.
2024-03-28 06:50:18,615 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:50:18] "POST /register HTTP/1.1" 200 -
2024-03-28 06:50:20,713 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:50:20] "GET /static/css/style.css HTTP/1.1" 200 -
2024-03-28 06:52:15,398 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:15] "GET /register HTTP/1.1" 200 -
2024-03-28 06:52:15,446 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2024-03-28 06:52:15,496 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-03-28 06:52:19,739 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:19] "GET /login HTTP/1.1" 200 -
2024-03-28 06:52:19,768 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2024-03-28 06:52:21,307 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:21] "POST /login HTTP/1.1" 200 -
2024-03-28 06:52:21,336 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2024-03-28 06:52:22,930 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:22] "GET /profile HTTP/1.1" 200 -
2024-03-28 06:52:22,959 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 06:52:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2024-03-28 10:01:02,222 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:01:02,222 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:01:38,456 ERROR app Exception on /post/user/get_all/0nIh1WakJiOikGchJye/site [GET]
Traceback (most recent call last):
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 892, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1183, in make_response
    rv = self.json.response(rv)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\json\provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type User is not JSON serializable
2024-03-28 10:01:38,488 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:01:38] "[35m[1mGET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1[0m" 500 -
2024-03-28 10:06:39,497 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:06:39,498 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:06:52,102 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:06:52] "GET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1" 200 -
2024-03-28 10:10:03,432 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:10:03,433 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:10:07,772 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:10:07] "GET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1" 200 -
2024-03-28 10:11:43,079 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:11:43,080 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:11:48,534 ERROR app Exception on /post/user/get_all/0nIh1WakJiOikGchJye/site [GET]
Traceback (most recent call last):
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\Documents\REST\app.py", line 217, in get_all_users_from_db
    user = User.query.all()
           ^^^^^^^^^^
AttributeError: type object 'User' has no attribute 'query'
2024-03-28 10:11:48,545 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:11:48] "[35m[1mGET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1[0m" 500 -
2024-03-28 10:12:49,384 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:12:49,384 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:12:52,696 ERROR app Exception on /post/user/get_all/0nIh1WakJiOikGchJye/site [GET]
Traceback (most recent call last):
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\Documents\REST\app.py", line 217, in get_all_users_from_db
    user = db_sess.query.all()
           ^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'all'
2024-03-28 10:12:52,697 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:12:52] "[35m[1mGET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1[0m" 500 -
2024-03-28 10:13:44,549 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:13:44,550 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:13:48,493 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:13:48] "GET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1" 200 -
2024-03-28 10:14:29,585 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:14:29,585 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:14:31,421 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:14:31] "GET /post/user/get_all/0nIh1WakJiOikGchJye/site HTTP/1.1" 200 -
2024-03-28 10:16:35,959 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:16:35] "GET /post/user/get_all/0nIh1WakJiOikGchJye/bot HTTP/1.1" 200 -
2024-03-28 10:18:51,902 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-03-28 10:18:51,902 INFO werkzeug [33mPress CTRL+C to quit[0m
2024-03-28 10:18:53,691 ERROR app Exception on /post/user/get_all/0nIh1WakJiOikGchJye/bot [GET]
Traceback (most recent call last):
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\3rd\Documents\REST\app.py", line 234, in get_all_users_from_db
    "name": us[1],
            ^^
UnboundLocalError: cannot access local variable 'us' where it is not associated with a value
2024-03-28 10:18:53,692 INFO werkzeug 127.0.0.1 - - [28/Mar/2024 10:18:53] "[35m[1mGET /post/user/get_all/0nIh1WakJiOikGchJye/bot HTTP/1.1[0m" 500 -
